version: "3.9"

services:
  db:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    voulmes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSAL_DATABASE: wordpress
      MYSQL_USER: bmaegan
      MYSQL_PASSWORD: 12345
  wp:
    depends-on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    #build: .
    ports:
      - "8080:80"
    restart: always
      #links:
      #  - redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: qwerty123
      WORDPRESS_DB_NAME: wordpress
  nginx:
    image:
volumes:
  db_data: {}
  wordpress_data: {}
