version: "3.9"

services:
  db:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    container_name: MariaDB
    #command:
    voulmes:
      - db_data:/var/lib/mysql
    #restart: always
    restart: unless-stopped
    #env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bmaegan
      MYSQL_PASSWORD: 12345
    networks:
      - app-network

  wp:
    depends-on:
      - db
    container_name: wordpress
    volumes:
      - ./mariadb/conf/wp_data:/var/www/html
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    env_file: .env
      #links:
      #  - redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: qwerty123
      WORDPRESS_DB_NAME: wordpress
    networks:
      - app-network

  nginx:
    depends_on:
      - wp
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports: 443:443
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

        #  phpmyadmin:
        #    image: phpmyadmin
        #    restart: always
        #    ports:
        #      - 8080:80
        #    environment:
        #      - PMA_ARBITRARY=1

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  app-network:
    driver: bridge

