version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools/cert/:/etc/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        DB_USER: ${DB_USER}
        DB_PWD: ${DB_PWD}
        DB_ROOT_PWD: ${DB_ROOT_PWD}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        DB_USER: ${DB_USER}
        DB_PWD: ${DB_PWD}
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: requirements/bonus/phpmyadmin/Dockerfile
    ports:
      - "3307:3307"
    networks:
     - inception
    restart: always

  website:
    container_name: website
    build:
      context: .
      dockerfile: requirements/bonus/website/Dockerfile
    ports:
      - "80:80"
    restart: always

  ftpserver:
    container_name: ftpserver
    build:
      context: .
      dockerfile: requirements/bonus/ftpserver/Dockerfile
      args:
        FTP_PWD: ${FTP_PWD}
    ports:
      - "23:23"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception
    restart: always


volumes:
  wp-volume:
#    external: true
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bmaegan/data/wordpress
  db-volume:
#    external: true
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bmaegan/data/mariadb


networks:
    inception:
        driver: bridge
