version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        HOSTNAME: ${MYSQL_HOSTNAME}
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: requirements/wordpress
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        WORDPRESS_TITLE: ${WORDPRESS_TITLE}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
    ports:
     - "9000:9000"
    networks:
      - inception
    volumes:
      - wp_volume:/var/www/html
    restart: always

#  redis:
#    container_name: redis
#    build:
#      context: .
#      dockerfile: requirements/bonus/redis/Dockerfile
#    ports:
#      - "6379:6379"
#    networks:
#      - inception
#    restart: always

#  adminer:
#    container_name: adminer
#    depends_on:
#      - mariadb
#    build:
#      context: .
#      dockerfile: requirements/bonus/adminer/Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#     - inception
#    restart: always

#  phpmyadmin:
#    container_name: phpmyadmin
#    depends_on:
#      - mariadb
#    build:
#      context: .
#      dockerfile: requirements/bonus/phpmyadmin/Dockerfile
#    ports:
#      - "3307:3307"
#    networks:
#     - inception
#    restart: always

#  website:
#    container_name: website
#    build:
#      context: .
#      dockerfile: requirements/bonus/website/Dockerfile
#    ports:
#      - "80:80"
#    restart: always

#  ftpserver:
#    container_name: ftpserver
#    build:
#      context: .
#      dockerfile: requirements/bonus/ftpserver/Dockerfile
#      args:
#        FTP_PWD: ${FTP_PWD}
#    ports:
#      - "23:23"
#    volumes:
#      - wp_volume:/var/www/
#    networks:
#     - inception
#    restart: always


volumes:
  wp_volume:
#    external: true
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bmaegan/data/wordpress
  mysql_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bmaegan/data/mariadb


networks:
    inception:
        driver: bridge
